In [3]:
#random vars :  W, I AND   X, Y
import numpy as np

In [5]:
prob_W_I=np.array([[1/2,0],[0,1/6],[0,1/3]])
print(prob_W_I)

[[ 0.5         0.        ]
 [ 0.          0.16666667]
 [ 0.          0.33333333]]


In [9]:
#Marginalization  ,   getting marginal  distros   pw and pI:
prob_W=prob_W_I.sum(axis=1)
print(prob_W)
prob_I=prob_W_I.sum(axis=0)
print(prob_I)

[ 0.5         0.16666667  0.33333333]
[ 0.5  0.5]


In [13]:
prob_W.shape

(3,)

In [26]:
temp=(prob_I.T)
temp=temp.reshape(1,2)


In [28]:
temp1=prob_W.reshape(3,1)

In [29]:
temp1*temp

array([[ 0.25      ,  0.25      ],
       [ 0.08333333,  0.08333333],
       [ 0.16666667,  0.16666667]])

In [30]:
#same thing as nupmpy outer

In [31]:
print(np.outer(prob_W,prob_I))

[[ 0.25        0.25      ]
 [ 0.08333333  0.08333333]
 [ 0.16666667  0.16666667]]


In [32]:
#that    must be  checked  with   joint probability    table(  the  joint  distribution is not a    probability table)

In [33]:
prob_W_I

array([[ 0.5       ,  0.        ],
       [ 0.        ,  0.16666667],
       [ 0.        ,  0.33333333]])

In [34]:
# must  be normalized   by dividing each row  to    corresponsing sum
 

In [35]:
np.sum(prob_W_I,axis=1)

array([ 0.5       ,  0.16666667,  0.33333333])

In [37]:
prob_W_I/np.sum(prob_W_I,axis=1)[:,None]

array([[ 1.,  0.],
       [ 0.,  1.],
       [ 0.,  1.]])

In [38]:
0.5/0.5

1.0

In [39]:
print(np.outer(prob_W, prob_I))

[[ 0.25        0.25      ]
 [ 0.08333333  0.08333333]
 [ 0.16666667  0.16666667]]


In [43]:
##############################
pxy=np.array([[1/4,1/4],[1/12,1/12],[1/6,1/6]])
pxy

array([[ 0.25      ,  0.25      ],
       [ 0.08333333,  0.08333333],
       [ 0.16666667,  0.16666667]])

In [44]:
#marginalization ( getting  px   and  py)

In [46]:
px=pxy.sum(axis=1)
px

array([ 0.5       ,  0.16666667,  0.33333333])

In [50]:
py=pxy.sum(axis=0)
py

array([ 0.5,  0.5])

In [51]:
print(np.outer(px,py))

[[ 0.25        0.25      ]
 [ 0.08333333  0.08333333]
 [ 0.16666667  0.16666667]]


In [52]:
pxy/np.sum(pxy,axis=1)[:,None]

array([[ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])