In [3]:
import numpy as np

In [4]:
import numpy as np

prob_space = {
    ('female', 'A', 'admitted'): 0.019566946531153304,
    ('female', 'A', 'rejected'): 0.004295183384887301,
    ('female', 'B', 'admitted'): 0.0037560760053027007,
    ('female', 'B', 'rejected'): 0.0017675651789660005,
    ('female', 'C', 'admitted'): 0.044547061422890007,
    ('female', 'C', 'rejected'): 0.086473707467962915,
    ('female', 'D', 'admitted'): 0.028999116217410508,
    ('female', 'D', 'rejected'): 0.053855501546619514,
    ('female', 'E', 'admitted'): 0.020839593460008802,
    ('female', 'E', 'rejected'): 0.065992045956694709,
    ('female', 'F', 'admitted'): 0.0052739726027397011,
    ('female', 'F', 'rejected'): 0.070068493150684918,
    ('male', 'A', 'admitted'): 0.11301369863013702,
    ('male', 'A', 'rejected'): 0.069266460450729109,
    ('male', 'B', 'admitted'): 0.077949624392399511,
    ('male', 'B', 'rejected'): 0.045779938135218703,
    ('male', 'C', 'admitted'): 0.026568714096332307,
    ('male', 'C', 'rejected'): 0.045238621299160404,
    ('male', 'D', 'admitted'): 0.030404330534688506,
    ('male', 'D', 'rejected'): 0.061730004418912916,
    ('male', 'E', 'admitted'): 0.011816173221387503,
    ('male', 'E', 'rejected'): 0.030384445426425107,
    ('male', 'F', 'admitted'): 0.0049447635881573011,
    ('male', 'F', 'rejected'): 0.077467962881131211
}


In [5]:
gender_labels = ['female', 'male']  # axis 0
department_labels = ['A', 'B', 'C', 'D', 'E', 'F']  # axis 1
admission_labels = ['admitted', 'rejected']  # axis 2

gender_mapping = {label: index
                  for index, label in enumerate(gender_labels)}
department_mapping = {label: index
                      for index, label in enumerate(department_labels)}
admission_mapping = {label: index
                     for index, label in enumerate(admission_labels)}

joint_prob_table = np.zeros((2, 6, 2))

# read information from full probability space into the joint probability table
for gender, department, admission in prob_space:
    joint_prob_table[gender_mapping[gender],
                     department_mapping[department],
                     admission_mapping[admission]] = prob_space[(gender,
                                                                 department,
                                                                 admission)]

In [6]:
#this  is conditioning  only  on  gender  and admission meaning dropping( summins  axis  w  which is  for dep)

In [7]:
#Pag
joint_prob_gender_admission = joint_prob_table.sum(axis=1)

In [8]:
admitted_only = joint_prob_gender_admission[:, admission_mapping['admitted']]

In [9]:
admitted_only

array([ 0.12298277,  0.2646973 ])

In [10]:
prob_gender_given_admitted = admitted_only / np.sum(admitted_only)

In [11]:
prob_gender_given_admitted_dict = dict(zip(gender_labels, prob_gender_given_admitted))
print(prob_gender_given_admitted_dict)

{'male': 0.68277253453699915, 'female': 0.31722746546300079}


In [77]:
#FEmALE DEPARTMENT
female_and_A_only = joint_prob_table[gender_mapping['female'], department_mapping['F']]

In [78]:
female_and_A_only

array([ 0.00527397,  0.07006849])

In [79]:
female_and_A_only_nporm=female_and_A_only/np.sum(female_and_A_only)

In [80]:
female_and_A_only_nporm

array([ 0.07,  0.93])

In [81]:
female_only=dict(zip(admission_labels,female_and_A_only_nporm))

In [82]:
female_only

{'admitted': 0.069999999999999701, 'rejected': 0.93000000000000027}

In [73]:
#MALE DEPARTMENT
male_and_A_only = joint_prob_table[gender_mapping['male'], department_mapping['F']]

In [74]:
male_and_A_only_nporm=male_and_A_only/np.sum(male_and_A_only)

In [75]:
male_only=dict(zip(admission_labels,male_and_A_only_nporm))

In [76]:
male_only

{'admitted': 0.05999999999999988, 'rejected': 0.94000000000000006}